/**
 * fixtures.ts — Load committed engine parity fixtures at test time.
 *
 * Fixtures live in tools/parity/fixtures/engine/<name>.idx.gz and were
 * generated by gen-fixture.ts from DOSBox-X save states. They are the
 * committed ground truth for what the engine renders.
 *
 * Exported API:
 *   loadFixture(name) → { indices: Uint8Array, rgba: Uint8Array }
 *   FIXTURE_NAMES — known fixture names
 *
 * No .sav file needed at test time. The fixture is a gzipped EGA index array
 * (64000 bytes raw = 320×200 pixels, one byte per pixel, values 0–15).
 * The RGBA is derived by applying the wiz6-main AC→DAC palette.
 */

import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { indicesToRgba } from './decode-screen.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const FIXTURES_DIR = resolve(__dirname, 'fixtures', 'engine');

/** Known fixture names — matches what gen-fixture.ts generated. */
export const FIXTURE_NAMES = [
  'character-menu-empty',
  'character-menu-partial',
  'character-menu-full',
] as const;

export type FixtureName = typeof FIXTURE_NAMES[number];

/**
 * Load a committed engine fixture by name.
 *
 * Reads `<name>.idx.gz`, decompresses to the raw EGA index array, then
 * applies the wiz6-main AC→DAC palette to produce RGBA.
 *
 * @param name  Fixture name (e.g. 'character-menu-partial')
 * @returns     { indices, rgba } — both Uint8Array, 64000 and 256000 bytes
 * @throws      If the fixture file doesn't exist or has wrong size after decompression
 */
export function loadFixture(name: string): {
  indices: Uint8Array;
  rgba: Uint8Array;
} {
  const idxGzPath = join(FIXTURES_DIR, `${name}.idx.gz`);
  const compressed = readFileSync(idxGzPath);
  const decompressed = gunzipSync(compressed);

  // Validate size: 320×200 = 64000 bytes
  if (decompressed.length !== 64000) {
    throw new Error(
      `loadFixture("${name}"): expected 64000 bytes after decompression, got ${decompressed.length}`,
    );
  }

  const indices = new Uint8Array(decompressed.buffer, decompressed.byteOffset, decompressed.byteLength);
  const rgba = indicesToRgba(indices);

  return { indices, rgba };
}

/**
 * Get the path to a fixture's PNG (for human viewing or Playwright attach).
 * The PNG must already exist (was generated by gen-fixture.ts).
 */
export function fixturePngPath(name: string): string {
  return join(FIXTURES_DIR, `${name}.png`);
}
